# Generated by Django 4.2 on 2023-04-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_users_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdblink', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=500)),
                ('poster', models.CharField(max_length=500)),
            ],
        ),
    ]
