# Generated by Django 4.2 on 2023-04-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
