# Generated by Django 4.2 on 2023-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_movies_imdbid_alter_movies_imdbscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='imdblink',
        ),
        migrations.AddField(
            model_name='movies',
            name='cast',
            field=models.TextField(default='Failed to load.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='crew',
            field=models.TextField(default='Failed to load.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='date',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='isAdult',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='numVotes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='otitle',
            field=models.CharField(default='Failed to load.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='runtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
