# Generated by Django 4.2 on 2023-04-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_movies_imdblink_movies_cast_movies_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='imdbid',
            field=models.CharField(max_length=10),
        ),
    ]
