# Generated by Django 4.2 on 2023-05-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_profile_email_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('movieId', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
