# Generated by Django 4.2 on 2023-05-09 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='movieId',
        ),
        migrations.RemoveField(
            model_name='list',
            name='userId',
        ),
        migrations.AddField(
            model_name='list',
            name='movie',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.movies'),
        ),
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
