# Generated by Django 4.2 on 2023-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_list_movie_alter_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array', models.BinaryField()),
            ],
        ),
    ]
